#This abstracts the generated source files in the design. DO NOT EDIT. This document is generated by PSoC Creator design builds.

GEN_SOURCE_DIR= Generated_Source/PSoC4

GEN_C_SOURCE_CortexM0p=\
	$(GEN_SOURCE_DIR)/IDAC7_Source.c\
	$(GEN_SOURCE_DIR)/IDAC7_Source_PM.c\
	$(GEN_SOURCE_DIR)/IDAC7_Sink.c\
	$(GEN_SOURCE_DIR)/IDAC7_Sink_PM.c\
	$(GEN_SOURCE_DIR)/Opamp_Vref.c\
	$(GEN_SOURCE_DIR)/Opamp_Vref_PM.c\
	$(GEN_SOURCE_DIR)/Opamp_TIA.c\
	$(GEN_SOURCE_DIR)/Opamp_TIA_PM.c\
	$(GEN_SOURCE_DIR)/Zout.c\
	$(GEN_SOURCE_DIR)/Zout_PM.c\
	$(GEN_SOURCE_DIR)/Opamp_Vout.c\
	$(GEN_SOURCE_DIR)/Opamp_Vout_PM.c\
	$(GEN_SOURCE_DIR)/Vref.c\
	$(GEN_SOURCE_DIR)/Vref_PM.c\
	$(GEN_SOURCE_DIR)/Zin.c\
	$(GEN_SOURCE_DIR)/Zin_PM.c\
	$(GEN_SOURCE_DIR)/Iout.c\
	$(GEN_SOURCE_DIR)/Iout_PM.c\
	$(GEN_SOURCE_DIR)/Vout.c\
	$(GEN_SOURCE_DIR)/Vout_PM.c\
	$(GEN_SOURCE_DIR)/Int_Ext_Clk.c\
	$(GEN_SOURCE_DIR)/Pin_Ext_Clk.c\
	$(GEN_SOURCE_DIR)/Pin_Ext_Clk_PM.c\
	$(GEN_SOURCE_DIR)/CyFlash.c\
	$(GEN_SOURCE_DIR)/CyLib.c\
	$(GEN_SOURCE_DIR)/cyPm.c\
	$(GEN_SOURCE_DIR)/cyutils.c\
	$(GEN_SOURCE_DIR)/CyDMA.c\
	$(GEN_SOURCE_DIR)/CyLFClk.c\
	$(GEN_SOURCE_DIR)/cy_em_eeprom.c

GEN_ASM_SOURCE_CortexM0p=\
	$(GEN_SOURCE_DIR)/CyBootAsmGnu.s

GEN_SEP_C_SOURCE_CortexM0p=\
	$(GEN_SOURCE_DIR)/cyfitter_cfg.c\
	$(GEN_SOURCE_DIR)/cymetadata.c\
	$(GEN_SOURCE_DIR)/Cm0plusStart.c

GEN_LIBS_CortexM0p=\

